FROM python:3.6.5
MAINTAINER Andreas Vlachos <a.vlachos@sheffield.ac.uk>

RUN apt-get update -y
RUN apt-get install -y git

RUN git clone https://andreasvlachos:VlachM0re@github.com/sheffieldnlp/cwi.git
RUN cd cwi
RUN pip install -r requirements_docker.txt

RUN python setup.py develop

RUN python -m spacy download de_core_news_sm
RUN python -m spacy download es_core_news_md
RUN python -m spacy download en_core_web_lg
RUN python -m spacy download fr_core_news_md
